[package]
name = "dpsim-api"
authors = ["Richard Marston <rmarston@eonerc.rwth-aachen.de>"]
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = { git = "https://github.com/SergioBenitez/Rocket", version = "0.5.0-dev" }
serde = { version = "^1", features = ["derive"] }
redis = "0.20.1"
log = "0.4.14"
doc-comment = "0.3.3"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
version = "0.5.0-dev"
default-features = false
features = ["json"]
